#!/bin/sh
#
# Script (AppleHDA) to patch AppleHDA so that it works with Mountain Lion DP2
#
# Version 0.2 - Copyright (c) 2012 by RevoGirl <DutchHockeyGoalie@yahoo.com>
#

#set -x # Used for tracing errors (can be put anywhere in the script).

#================================= GLOBAL VARS ==================================

targetVolume="/Volumes/Mountain Lion"

FILENAME="/AppleHDA.kext/Contents/MacOS/AppleHDA"

#
# Check if FileGuard is setup.
#
if [ -d /Extra/FileGuard/Files/System/Library/Extensions ];
    then
        #
        # Yes, then use that path.
        #
        TARGET_PATH="${targetVolume}/Extra/FileGuard/Files/System/Library/Extensions"
    else
        #
        # No, use the normal extensions path.
        #
        TARGET_PATH="${targetVolume}/System/Library/Extensions"
fi

TARGET_FILE="${TARGET_PATH}${FILENAME}"

#=============================== LOCAL FUNCTIONS ================================

function _notAlreadyPatched()
{
  echo 1 # RFE: Implement me.
}

#--------------------------------------------------------------------------------

function main()
{
  if [ _notAlreadyPatched -eq 1 ]; then
    /usr/bin/perl -pi -e 's|\xff\x87\xec\x1a\x0f\x8f\xba\x01\x00\x00|\x92\x08\xec\x10\x0f\x84\xc4\x03\x00\x00|g' $TARGET_FILE
    /usr/bin/perl -pi -e 's|\x74\x19\xad\x15\x0f\x8f\x87\x01\x00\x00|\x98\x08\xec\x10\x0f\x84\xb8\x03\x00\x00|g' $TARGET_FILE

    /usr/bin/perl -pi -e 's|\xff\x87\xec\x1a\x0f\x8f\xa1\x01\x00\x00|\x92\x08\xec\x10\x0f\x84\x88\x03\x00\x00|g' $TARGET_FILE
    /usr/bin/perl -pi -e 's|\x74\x19\xad\x15\x0f\x8f\x6e\x01\x00\x00|\x98\x08\xec\x10\x0f\x84\x7c\x03\x00\x00|g' $TARGET_FILE

    /usr/bin/perl -pi -e 's|\xff\x87\xec\x1a\x0f\x8f\xa7\x01\x00\x00|\x92\x08\xec\x10\x0f\x84\x68\x03\x00\x00|g' $TARGET_FILE
    /usr/bin/perl -pi -e 's|\x74\x19\xad\x15\x0f\x8f\x77\x01\x00\x00|\x98\x08\xec\x10\x0f\x84\x5d\x03\x00\x00|g' $TARGET_FILE

    /usr/bin/perl -pi -e 's|\xff\x87\xec\x1a\x0f\x8f\x91\x01\x00\x00|\x92\x08\xec\x10\x0f\x84\x4a\x03\x00\x00|g' $TARGET_FILE
    /usr/bin/perl -pi -e 's|\x74\x19\xad\x15\x0f\x8f\x61\x01\x00\x00|\x98\x08\xec\x10\x0f\x84\x3f\x03\x00\x00|g' $TARGET_FILE
  fi
}

#--------------------------------------------------------------------------------
#
# Only administrators (root) are allowed to run this script.
#
#--------------------------------------------------------------------------------

function _isRoot()
{
  if [ $(id -u) != 0 ]; then
      echo "This script must be run as root" 1>&2
      exit 1
  fi

  echo 1
}

#==================================== START =====================================

if [ $(_isRoot) ]; then
  main
fi

#================================================================================

exit 0
